name: Distribute Chipmunk on RPM/YUM
run-name: chipmunk rpm package creation and publish to repository
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create RPM package
        run: |
          bash distribute_to_rpm.sh

      - name: Push RPM package to chipmunk assets
        run: |
          bash rpm_rhel/push_to_chipmunk_assets.sh

      - name: Create and publish repo to yum
        run: |
          bash rpm_rhel/publish_repo.sh