name: Distribute Chipmunk on APT/Debian
run-name: chipmunk apt package creation and publish to debian repository
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Runner Version
        run: echo "Runner version:$(./svc.sh --version)"

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get release
        run: | 
           bash apt/scripts/get_release.sh

      - name: Prepare environment
        id: prepare
        run: |
          bash apt/scripts/untar_release.sh /tmp/chipmunk_work_dir/chipmunk@3.10.3-linux-portable.tar.gz
          echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Build .deb package
        run: |
           echo $WORK_DIR
           cd $WORK_DIR
           pwd
           sudo bash apt/scripts/build_deb_package.sh ../package

    #   - name: Push .deb package to chipmunk assets
    #     run: |
    #         bash rpm_rhel/push_to_chipmunk_assets
    



