name: Distribute Chipmunk on chocolatey
run-name: chipmunk package creation and publish on chocolatey
on: [push]

jobs:
  distribute:
    runs-on: windows-latest
    steps:

    - name: Package and publish
      run: pwsh .\distribute_to_chocolatey.ps1 -publish