name: Distribute Chipmunk on APT/Debian
run-name: chipmunk apt package creation and publish to debian repository
on:
  push:
    tags:
      - "*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential fakeroot devscripts debhelper dh-make git 

      - name: Get release
        run: | 
          bash apt/scripts/get_release.sh

      - name: Prepare environment
        id: prepare
        run: | 
            bash apt/scripts/untar_release.sh ${{env.TAR_FILE}}  
        env:
            TAR_FILE: ${{ env.TAR_FILE }}

      - name: Build .deb package
        run: |
          sudo bash apt/scripts/build_deb_package.sh ../package ${{env.VERSION}}
      
      - name: list deb package
        working-directory: .
        run: |
          cd package
          echo "DEB_FILE=$(find -type f -name '*.deb' -printf '%f\n')" >> $GITHUB_ENV

      - name: list tag_name
        run: |
          echo ${{ github.ref_name }}
      
      - name: Upload deb to chipmunk using overwrite functionality
        id: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: esrlabs/chipmunk
          repo_token: ${{ secrets.CHIPMUNK_TOKEN }}
          file: ./package/${{ env.DEB_FILE }}
          asset_name: ${{ env.DEB_FILE }}
          tag: ${{ github.ref_name }}
          overwrite: true

