name: Distribute Chipmunk on RPM/YUM
run-name: chipmunk rpm package creation and publish to repository
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create RPM package
        run: |
          bash distribute_to_rpm.sh

      - name: list RPM package
        working-directory: .
        run: ls

      - name: Get release information from chipmunk
        id: get_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ secrets.CHIPMUNK_TOKEN }}
          owner: esrlabs
          repo: chipmunk
          tag_name: dummy-3.10.3

      - name: Read output of get release
        run: echo "${{ steps.get_release.outputs.upload_url }}"

      - name: Upload RPM to chipmunk
        id: upload_rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CHIPMUNK_TOKEN }}
        with:
          token: ${{ secrets.CHIPMUNK_TOKEN }}
          owner: esrlabs
          repo: chipmunk
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: .
          asset_name: "*.x86_64.rpm"
          asset_content_type: application/x-rpm

      # - name: upload RPM package to chipmunk
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: "./application/holder/release/*.tgz;./application/holder/release/*.zip"
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     release-tag: ${{ github.ref_name }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload File
      #   id: upload
      #   uses: JantHsueh/upload-file-action@master
      #   with:
      #     url: https://www.pgyer.com/apiv2/app/upload
      #     forms: '{"_api_key":"${{ secrets.pgyer_key }}","buildInstallType":3}'
      #     fileForms: '{"file":"app/build/outputs/apk/release/app-release.apk"}'

      # - name: upload RPM package to chipmunk
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ./*.rpm
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "This is my release text"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push RPM package to chipmunk assets
        run: |
          bash rpm_rhel/push_to_chipmunk_assets.sh

      - name: Create and publish repo to yum
        run: |
          bash rpm_rhel/publish_repo.sh