name: Distribute Chipmunk on APT/Debian
run-name: chipmunk apt package creation and publish to debian repository
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get release
        run: | 
          bash apt/scripts/get_release.sh

      - name: Prepare environment
        id: prepare
        uses: actions/checkout@v2  # Checkout code into the workspace
        with:
            path: chipmunk_workspace  # Set workspace path
      - run: |
            cd chipmunk_workspace
            bash apt/scripts/untar_release.sh /tmp/chipmunk_work_dir/chipmunk@3.10.3-linux-portable.tar.gz

      - name: Build .deb package
        run: |
          cd $WORK_DIR
          ls -l
          cd chipmunk
          pwd
          sudo bash apt/scripts/build_deb_package.sh ../package