name: Distribute Chipmunk on APT/Debian
run-name: chipmunk apt package creation and publish to debian repository
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Prepare environment
        run: |
          pwd
          bash apt/scripts/untar_release.sh

      - name: Build .deb package
        run: |
            bash apt/scripts/build_deb_package.sh

    #   - name: Push .deb package to chipmunk assets
    #     run: |
    #         bash rpm_rhel/push_to_chipmunk_assets
    



