name: Distribute Chipmunk on APT/Debian
run-name: chipmunk apt package creation and publish to debian repository
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential fakeroot devscripts debhelper dh-make git 

      - name: Get release
        run: | 
          bash apt/scripts/get_release.sh

      - name: Prepare environment
        id: prepare
        uses: actions/checkout@v2  # Checkout code into the workspace
        with:
            path: chipmunk_workspace  # Set workspace path
      - run: | 
            cd chipmunk_workspace
            bash apt/scripts/untar_release.sh /tmp/chipmunk_work_dir/chipmunk@3.10.3-linux-portable.tar.gz  

      - name: Build .deb package
        run: |
          sudo bash apt/scripts/build_deb_package.sh ../package
      
      - name: list RPM package
        working-directory: .
        run: |
          cd package
          ls -l
          echo "DEB_FILE=package/$(find package -type f -name '*_amd64.deb' -printf '%f\n')" >> $GITHUB_ENV
      
      - name: Upload deb to chipmunk using overwrite functionality
        id: upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: esrlabs/chipmunk
          repo_token: ${{ secrets.CHIPMUNK_TOKEN }}
          file: ./package/${{ env.DEB_FILE }}
          asset_name: ${{ env.DEB_FILE }}
          tag: dummy-3.10.3
          overwrite: true

