name: Distribute Chipmunk on RPM/YUM
run-name: chipmunk rpm package creation and publish to repository
on:
  push:
    tags:
      - "*"

jobs:
  build_x86_64:
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create RPM package
        run: |
          bash distribute_to_rpm.sh

      - name: list RPM package
        working-directory: .
        run: |
          echo "RPM_FILE=$(find -type f -name '*-x86_64.rpm' -printf '%f\n')" >> $GITHUB_ENV

      - name: list tag_name
        run: |
          echo ${{ github.ref_name }}

      - name: Upload RPM to chipmunk using overwrite functionality
        id: upload_rpm
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: esrlabs/chipmunk
          repo_token: ${{ secrets.CHIPMUNK_TOKEN }}
          file: ./${{ env.RPM_FILE }}
          asset_name: ${{ env.RPM_FILE }}
          tag: ${{ github.ref_name }}
          overwrite: true

  build_arm64:
    runs-on: ubuntu-22.04
    name: Build on ubuntu-latest aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Fetch architecture
        id: get_uname
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Create RPM package
        run: |
          bash distribute_to_rpm_arm64.sh

      - name: list RPM package
        working-directory: .
        run: |
          echo "RPM_FILE=$(find -type f -name '*-arm64.rpm' -printf '%f\n')" >> $GITHUB_ENV

      - name: list tag_name
        run: |
          echo ${{ github.ref_name }}

      - name: Upload RPM to chipmunk using overwrite functionality
        id: upload_rpm
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: esrlabs/chipmunk
          repo_token: ${{ secrets.CHIPMUNK_TOKEN }}
          file: ./${{ env.RPM_FILE }}
          asset_name: ${{ env.RPM_FILE }}
          tag: ${{ github.ref_name }}
          overwrite: true
